spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
            filters:
              - JwtFilter

          - id: security-service
            uri: lb://security-service
            predicates:
                - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
