spring:
  application:
    name: order-service


  datasource:
    url: jdbc:mysql://46.101.162.231:3306
    username: miracle
    password: miracle
    driver-class-name: com.mysql.jdbc.Driver

  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0