server:
  port: 0

spring:
  application:
    name: security-service

logging:
  level:
    com.socompany.securityservice.client.UserServiceClient: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${random.int[1,999]}