spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://46.101.162.231:3306/user-service
    username: miracle
    password: miracle

  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0